//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Company1 = new HashSet<Company>();
            this.Vending = new HashSet<Vending>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Code { get; set; }
        public int StatusId { get; set; }
        public string WebsiteAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        public virtual StatusCompany StatusCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vending> Vending { get; set; }
    }
}
