//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vending()
        {
            this.ProductInVending = new HashSet<ProductInVending>();
            this.Sales = new HashSet<Sales>();
            this.Service = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public string Place { get; set; }
        public string Address { get; set; }
        public int ModelId { get; set; }
        public int TypeId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateInstall { get; set; }
        public int ModemId { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Model Model { get; set; }
        public virtual Modem Modem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInVending> ProductInVending { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
